artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://elasticbeanstalk-eu-west-2-854337983934.s3.eu-west-2.amazonaws.com/Recycle_Data.zip
  local_data_file: artifacts/data_ingestion/Recycle_Data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
